### ISSUE TITLE
Server fault

### ISSUE THREAD

**Issue by Explorare** [mengskysama/FoobarTTLyric#1]
ping 174.140.165.4
time out.
( ´_ゝ`)

**Comment by Explorare** [comment]
百度音乐歌词伺服器IP
搜寻用IP>>123.125.114.237:80
下载IP>>180.76.22.49

**Comment by mengskysama** [comment]
一年前已经移到了
tt.mengsky.net

**Comment by Explorare** [comment]
你好

关于新版的使用方法有些疑问。首先我按照usage安装了crack版的插件，重新打开foobar并设定了歌词伺服器，如图001.

但我发现我的歌词面板菜单和你演示的略有不同，没有LyricSearch选项，不能自定义搜索关键词。

而且搜索一直是失败，我已清除了hosts中的无效IP。

问题出在哪里了呢？请赐教。

谢

发件人: mengskysama [mailto:notifications@github.com] 
发送时间: 2015年3月15日 20:41
收件人: mengskysama/FoobarTTLyric
抄送: Explorare
主题: Re: [FoobarTTLyric] Server fault (#1)

一年前已经移到了
tt.mengsky.net

**Comment by mengskysama** [comment]
我现在foobar是1.3.2
在歌词面板那右键没有Lyric Search这个选项嘛？

**Comment by Explorare** [comment]
抱歉刚才竟然没注意到那个选项，已经找到了，看来我需要去A岛看眼科了( ´_ゝ`)
现在数据库用的百度的？感觉匹配成功率低了好多是我的错觉么？好多新歌都没歌词，今年发售的大部分新番专集都没歌词，我手动改了关键词也没有。感觉没千千的好使了，不愉快desu

**Comment by mengskysama** [comment]
现在用千千的
